robotis_mini:
  #controller params
  pid_params: &id001
    p: 4.0
    i: 0.0
    d: 0.01
    
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  l_shoulder_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_shoulder_joint
    pid: *id001
  r_shoulder_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_shoulder_joint
    pid: *id001
  l_biceps_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_biceps_joint
    pid: *id001
  r_biceps_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_biceps_joint
    pid: *id001
  l_elbow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_elbow_joint
    pid: *id001
  r_elbow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_elbow_joint
    pid: *id001
  l_hip_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_hip_joint
    pid: *id001
  r_hip_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_hip_joint
    pid: *id001
  l_thigh_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_thigh_joint
    pid: *id001
  r_thigh_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_thigh_joint
    pid: *id001
  l_knee_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_knee_joint
    pid: *id001
  r_knee_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_knee_joint
    pid: *id001
  l_ankle_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_ankle_joint
    pid: *id001
  r_ankle_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_ankle_joint
    pid: *id001
  l_foot_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_foot_joint
    pid: *id001
  r_foot_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_foot_joint
    pid: *id001

